COMPANIES = [
    'Facebook',
    'Apple',
    'Amazon',
    'Netflix',
    'Google',
    'Microsoft',
    'Bloomberg',
    'Quora',
    'MITRE',
    'IBM',
    'SAP',
    'Cisco',
    'Lyft',
    'Airbnb',
    'Qualcomm',
    'Citadel',
    'Jane Street',
    'Two Sigma',
    'Goldman Sachs',
    'Morgan Stanley',
    'JP Morgan',
    'Hedge Fund',
    'Prop Trading',
    'Trading Firm',
    'Prop Shop',
    'Proprietary Trading',
    'HFT',
    'NASA',
    'Tesla',
    'Uber',
    'Intuit',
    'Yelp',
    'Yext',
    'Atlassian',
    'Telecom',
    'Square',
    'Fintech',
    'Capital One',
    'Stripe',
    'Barclays',
    'Rubrik',
    'Intel',
    'Asana',
    'VMware',
    'AT&T',
    'Oil',
    'Nvidia',
    'Blackrock',
    'Credit Karma',
    'Dropbox',
    'TripAdivsor',
    'Optiver',
    'Nextdoor',
    'Redfin',
    'Zillow',
    'Workday',
    'Digital Ocean',
    'Datadog',
    'Shopify',
    'Zendesk',
    'GitHub',
    'PayPal',
    'Snapchat',
    'MongoDB',
    'Salesforce',
    'Pinterest',
    'Yahoo',
    'Flexport',
    'SurveyMonkey',
    'Cruise',
    'Flatiron Health',
]
