COMPANIES = [
    'Facebook',
    'Apple',
    'Amazon',
    'Google',
    'Microsoft',
    'LinkedIn',
    'Twitter',
    'GitHub',
    'Bloomberg',
    'Quora',
    'MITRE',
    'IBM',
    'Cisco',
    'Lyft',
    'Uber',
    'Lime',
    'Bird',
    'Airbnb',
    'Citadel',
    'Jane Street',
    'Two Sigma',
    '2 Sigma',
    'DRW',
    'AQR',
    'Bridgewater Associates',
    'Akuna Capital',
    'Virtu Financial',
    'Hudson River Trading',
    'Goldman Sachs',
    'Morgan Stanley',
    'JP Morgan',
    'JPMorgan',
    'Citi',
    'Citigroup',
    'Bank of America',
    'Capital One',
    'Barclays',
    'Hedge Fund',
    'Prop Trading',
    'Trading Firm',
    'Prop Shop',
    'Proprietary Trading',
    'HFT',
    'NASA',
    'Tesla',
    'Intuit',
    'Yelp',
    'Yext',
    'Atlassian',
    'Square',
    'Palantir',
    'Stripe',
    'Rubrik',
    'Intel',
    'Asana',
    'VMware',
    'AT&T',
    'Verizon',
    'Nvidia',
    'Blackrock',
    'Credit Karma',
    'Dropbox',
    'Box',
    'Squarespace',
    'TripAdvisor',
    'Optiver',
    'Nextdoor',
    'Redfin',
    'Zillow',
    'Workday',
    'Digital Ocean',
    'DigitalOcean',
    'Pure Storage',
    'PureStorage',
    'Datadog',
    'Shopify',
    'Zendesk',
    'PayPal',
    'Snapchat',
    'Snap',
    'Snap Inc',
    'MongoDB',
    'Salesforce',
    'Pinterest',
    'Yahoo',
    'Flexport',
    'SurveyMonkey',
    'Cruise',
    'Flatiron Health',
    'Cloudera',
    'Foursquare',
    'Tableau',
    'Riot',
    'Lockheed Martin',
    'Raytheon',
    'Boeing',
    'Northrop Grumman',
    'United Technologies',
    'Oracle',
    'American Express',
    'Visa',
    'Epic',
    'Slack',
    'Walmart Labs',
    'ViaSat',
    'Coursera',
    'HubSpot',
    'Groupon',
    'Qualtrics',
    'Blend Labs',
    'Insurance',
    'Oil',
    'Telecom',
]


def combine_synonyms(company):
    if company == 'JP Morgan':
        company = 'JPMorgan'
    if company == 'Digital Ocean':
        company = 'DigitalOcean'
    if company in ['Proprietary Trading', 'Trading Firm', 'Prop Shop']:
        company = 'Prop Trading'
    if company == '2 Sigma':
        company = 'Two Sigma'
    if company == 'Pure Storage':
        company = 'PureStorage'
    if company in ['Snapchat', 'Snap', 'Snap Inc']:
        company = 'Snap Inc.'
    if company == 'Citi':
        company = 'Citigroup'
    # if company == 'Hudson River Trading':
    #     company = 'Hud. River Trading'
    return company
